workflows:
  build-android:
    name: Build Android APK
    environment:
      flutter: 3.24.0   # إصدار Flutter حديث يدعم كل شيء
    scripts:
      - flutter pub get
      - flutter build apk --release --android-skip-build-dependency-validation
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
